import AppKit
import SwiftUI

/// Settings tab for managing the device-pairing pre-shared key.
struct PairingSettingsView: View {
  // MARK: - State

  @ObservedObject private var pairing = PairingStore.shared

  @State private var showGenerateSheet = false
  @State private var showEnterSheet = false
  @State private var showUnpairAlert = false

  // MARK: - Body

  var body: some View {
    Group {
      if pairing.isPaired {
        pairedView
      } else {
        unpairedView
      }
    }
    .padding()
    .sheet(isPresented: $showGenerateSheet) {
      GenerateCodeSheet(isPresented: $showGenerateSheet)
    }
    .sheet(isPresented: $showEnterSheet) {
      EnterCodeSheet(isPresented: $showEnterSheet)
    }
    .alert(isPresented: $showUnpairAlert) {
      Alert(
        title: Text("Unpair this device?"),
        message: Text(
          "Blue Switch will stop accepting commands from your other Mac until you pair again."
        ),
        primaryButton: .destructive(Text("Unpair")) {
          pairing.unpair()
        },
        secondaryButton: .cancel()
      )
    }
  }

  // MARK: - Subviews

  private var unpairedView: some View {
    VStack(alignment: .leading, spacing: 16) {
      Text("Not paired")
        .font(.title2)
        .bold()
      Text("Pair this Mac with another Blue Switch install to enable secure switching.")
        .foregroundColor(.secondary)
      HStack {
        Button("Generate Code") {
          showGenerateSheet = true
        }
        .help("Create a new pairing code to enter on your other Mac.")
        Button("Enter Code") {
          showEnterSheet = true
        }
        .help("Enter a pairing code generated by your other Mac.")
      }
      Spacer()
    }
    .frame(maxWidth: .infinity, alignment: .leading)
  }

  private var pairedView: some View {
    VStack(alignment: .leading, spacing: 16) {
      Text("Paired")
        .font(.title2)
        .bold()
      if let fingerprint = pairing.fingerprint {
        VStack(alignment: .leading, spacing: 4) {
          Text("Fingerprint")
            .font(.caption)
            .foregroundColor(.secondary)
          Text(fingerprint)
            .font(.system(.title3, design: .monospaced))
        }
      }
      Text("Verify the same fingerprint appears on your other Mac.")
        .foregroundColor(.secondary)
      Button("Unpair") {
        showUnpairAlert = true
      }
      .foregroundColor(.red)
      .help("Remove the saved pairing key. This Mac will stop accepting commands.")
      Spacer()
    }
    .frame(maxWidth: .infinity, alignment: .leading)
  }
}

// MARK: - Selectable code helper

extension View {
  /// Applies `.textSelection(.enabled)` on macOS 12+, no-op otherwise. The
  /// project's deployment target still includes 11.x where the modifier
  /// isn't available.
  @ViewBuilder
  func userSelectable() -> some View {
    if #available(macOS 12.0, *) {
      self.textSelection(.enabled)
    } else {
      self
    }
  }
}

private func copyToPasteboard(_ text: String) {
  let pb = NSPasteboard.general
  pb.clearContents()
  pb.setString(text, forType: .string)
}

// MARK: - Generate Code Sheet

private struct GenerateCodeSheet: View {
  @Binding var isPresented: Bool
  @ObservedObject private var pairing = PairingStore.shared
  @State private var code: String = ""
  @State private var errorMessage: String?
  @State private var isPairing = false

  private var formattedCode: String {
    PairingStore.formatCode(code)
  }

  var body: some View {
    VStack(spacing: 20) {
      Text("Pairing Code")
        .font(.headline)
      Text(formattedCode)
        .font(.system(size: 32, weight: .bold, design: .monospaced))
        .userSelectable()
        .accessibilityLabel("Pairing code: \(formattedCode)")
      HStack {
        Button {
          copyToPasteboard(formattedCode)
        } label: {
          Label("Copy", systemImage: "doc.on.doc")
        }
        .help("Copy the pairing code to the clipboard.")
        .accessibilityLabel("Copy pairing code")
      }
      Text("Enter this code on your other Mac.")
        .foregroundColor(.secondary)
        .font(.caption)
      if let error = errorMessage {
        Text(error)
          .foregroundColor(.red)
          .font(.caption)
      }
      HStack {
        if isPairing {
          ProgressView()
            .controlSize(.small)
        }
        Spacer()
        Button("Cancel") {
          isPresented = false
        }
        .disabled(isPairing)
        .help("Close without saving this code.")
        Button("I've entered this on my other Mac") {
          startPair()
        }
        .keyboardShortcut(.defaultAction)
        .disabled(isPairing)
        .help("Save this code as the pairing key on this Mac.")
      }
    }
    .padding(24)
    .frame(width: 460)
    .onAppear {
      code = PairingStore.generateCode()
      errorMessage = nil
      isPairing = false
    }
  }

  private func startPair() {
    isPairing = true
    errorMessage = nil
    pairing.pair(withCode: code) { result in
      isPairing = false
      switch result {
      case .success:
        isPresented = false
      case .failure:
        errorMessage = "Failed to save pairing key."
      }
    }
  }
}

// MARK: - Enter Code Sheet

private struct EnterCodeSheet: View {
  @Binding var isPresented: Bool
  @ObservedObject private var pairing = PairingStore.shared
  @State private var input: String = ""
  @State private var errorMessage: String?
  @State private var isPairing = false

  var body: some View {
    VStack(spacing: 20) {
      Text("Enter Pairing Code")
        .font(.headline)
      TextField("XXXX-XXXX-XXXX", text: $input)
        .textFieldStyle(RoundedBorderTextFieldStyle())
        .font(.system(.title2, design: .monospaced))
        .disabled(isPairing)
        .onChange(of: input) { newValue in
          let normalized = PairingStore.normalize(newValue)
          let limited = String(normalized.prefix(PairingStore.codeLength))
          let formatted = PairingStore.formatCode(limited)
          if formatted != newValue {
            input = formatted
          }
        }
      if let error = errorMessage {
        Text(error)
          .foregroundColor(.red)
          .font(.caption)
      }
      HStack {
        if isPairing {
          ProgressView()
            .controlSize(.small)
        }
        Spacer()
        Button("Cancel") {
          isPresented = false
        }
        .disabled(isPairing)
        .help("Close without pairing.")
        Button("Pair") {
          startPair()
        }
        .keyboardShortcut(.defaultAction)
        .disabled(isPairing)
        .help("Save the entered code as the pairing key on this Mac.")
      }
    }
    .padding(24)
    .frame(width: 420)
  }

  private func startPair() {
    let normalized = PairingStore.normalize(input)
    guard PairingStore.isValid(normalized) else {
      errorMessage = "Code must be 12 characters from the pairing alphabet."
      return
    }
    isPairing = true
    errorMessage = nil
    pairing.pair(withCode: normalized) { result in
      isPairing = false
      switch result {
      case .success:
        isPresented = false
      case .failure(let err):
        switch err {
        case .invalidCode:
          errorMessage = "Invalid code."
        case .derivationFailed:
          errorMessage = "Couldn't derive a key from that code."
        case .keychainFailed(let status):
          errorMessage = "Couldn't save the key to the keychain (error \(status))."
        }
      }
    }
  }
}

// MARK: - Preview

#Preview {
  PairingSettingsView()
}
