import AppKit
import SwiftUI

/// Settings tab for managing the device-pairing pre-shared key.
struct PairingSettingsView: View {
  // MARK: - State

  @ObservedObject private var pairing = PairingStore.shared
  @ObservedObject private var networkStore = NetworkDeviceStore.shared

  @State private var showGenerateSheet = false
  @State private var showEnterSheet = false
  @State private var showUnpairAlert = false
  @State private var unpairErrorStatus: OSStatus?

  // MARK: - Body

  var body: some View {
    Group {
      if pairing.isPaired {
        pairedView
      } else {
        unpairedView
      }
    }
    .padding()
    .sheet(isPresented: $showGenerateSheet) {
      GenerateCodeSheet(isPresented: $showGenerateSheet)
    }
    .sheet(isPresented: $showEnterSheet) {
      EnterCodeSheet(isPresented: $showEnterSheet)
    }
    .alert(isPresented: $showUnpairAlert) {
      Alert(
        title: Text("Unpair this device?"),
        message: Text(
          "Magic Switch will stop accepting commands from your other Mac until you pair again."
        ),
        primaryButton: .destructive(Text("Unpair")) {
          unpairErrorStatus = nil
          pairing.unpair { status in
            unpairErrorStatus = status
          }
        },
        secondaryButton: .cancel()
      )
    }
  }

  // MARK: - Subviews

  private var unpairedView: some View {
    VStack(alignment: .leading, spacing: 16) {
      Text("Not paired")
        .font(.title2)
        .bold()
      Text("Pair this Mac with another Magic Switch install to enable secure switching.")
        .foregroundColor(.secondary)
      HStack {
        Button("Generate Code") {
          showGenerateSheet = true
        }
        .help("Create a new pairing code to enter on your other Mac.")
        Button("Enter Code") {
          showEnterSheet = true
        }
        .help("Enter a pairing code generated by your other Mac.")
      }
      Spacer()
    }
    .frame(maxWidth: .infinity, alignment: .leading)
  }

  private var pairedView: some View {
    VStack(alignment: .leading, spacing: 16) {
      Text("Paired")
        .font(.title2)
        .bold()
      if networkStore.networkDevices.isEmpty {
        // Mirrors the prerequisite hint on the Device tab — accent-coloured
        // Label so the "do this next" affordance reads as actionable
        // instead of looking like throwaway helper text.
        Label(
          "Now pick the other Mac in Settings → Device to start switching.",
          systemImage: "arrow.right.circle.fill"
        )
        .font(.callout.bold())
        .foregroundColor(.accentColor)
      }
      if let fingerprint = pairing.fingerprint {
        VStack(alignment: .leading, spacing: 4) {
          Text("Your fingerprint")
            .font(.caption)
            .foregroundColor(.secondary)
          Text(fingerprint)
            .font(.system(.title3, design: .monospaced))
        }
      }
      Text("Compare with the fingerprint shown on your other Mac — they should match.")
        .foregroundColor(.secondary)
      Button("Unpair") {
        showUnpairAlert = true
      }
      .foregroundColor(.red)
      .help("Remove the saved pairing key. This Mac will stop accepting commands.")
      if let status = unpairErrorStatus {
        Text("Couldn't unpair: keychain returned error \(status).")
          .foregroundColor(.red)
          .font(.caption)
      }
      Spacer()
    }
    .frame(maxWidth: .infinity, alignment: .leading)
  }
}

// MARK: - Selectable code helper

extension View {
  /// Applies `.textSelection(.enabled)` on macOS 12+, no-op otherwise. The
  /// project's deployment target still includes 11.x where the modifier
  /// isn't available.
  @ViewBuilder
  func userSelectable() -> some View {
    if #available(macOS 12.0, *) {
      self.textSelection(.enabled)
    } else {
      self
    }
  }
}

private func copyToPasteboard(_ text: String) {
  let pb = NSPasteboard.general
  pb.clearContents()
  pb.setString(text, forType: .string)
}

// MARK: - Generate Code Sheet

private struct GenerateCodeSheet: View {
  @Binding var isPresented: Bool
  @ObservedObject private var pairing = PairingStore.shared
  @State private var code: String = ""
  @State private var errorMessage: String?
  @State private var saveState: SaveState = .saving

  /// Progress of the auto-save kicked off in `onAppear`. The Done button is
  /// gated on `.saved` so the user can't dismiss with the keychain write
  /// still in flight (which would leave us thinking we're paired before
  /// PBKDF2 finishes).
  private enum SaveState {
    case saving
    case saved
    case failed
  }

  private var formattedCode: String {
    PairingStore.formatCode(code)
  }

  var body: some View {
    VStack(spacing: 20) {
      Text("Pairing Code")
        .font(.headline)
      Text(formattedCode)
        .font(.system(size: 32, weight: .bold, design: .monospaced))
        .userSelectable()
        .accessibilityLabel("Pairing code: \(formattedCode)")
      HStack {
        Button {
          copyToPasteboard(formattedCode)
        } label: {
          Label("Copy", systemImage: "doc.on.doc")
        }
        .help("Copy the pairing code to the clipboard.")
        .accessibilityLabel("Copy pairing code")
      }
      Text(
        "Enter this code on your other Mac. Order doesn't matter — both Macs derive the same key from the same code."
      )
      .foregroundColor(.secondary)
      .font(.caption)
      .multilineTextAlignment(.center)
      if let error = errorMessage {
        Text(error)
          .foregroundColor(.red)
          .font(.caption)
      }
      HStack {
        if saveState == .saving {
          ProgressView()
            .controlSize(.small)
          Text("Saving…")
            .font(.caption)
            .foregroundColor(.secondary)
        }
        Spacer()
        Button("Discard") {
          discard()
        }
        .help("Remove the saved key from this Mac and close.")
        Button("Done") {
          isPresented = false
        }
        .keyboardShortcut(.defaultAction)
        .disabled(saveState != .saved)
        .help("Close. The pairing key stays saved on this Mac.")
      }
    }
    .padding(24)
    .frame(width: 460)
    .onAppear {
      generateAndSave()
    }
  }

  /// Generate the code and persist it immediately. This removes the failure
  /// mode where a user generated a code, shared it with the peer, the peer
  /// pair'd, then this side cancelled the sheet without saving — leaving
  /// the peer paired alone and confusing the first handshake.
  private func generateAndSave() {
    code = PairingStore.generateCode()
    errorMessage = nil
    saveState = .saving
    pairing.pair(withCode: code) { result in
      switch result {
      case .success:
        saveState = .saved
      case .failure:
        saveState = .failed
        errorMessage = "Failed to save pairing key."
      }
    }
  }

  private func discard() {
    pairing.unpair { _ in
      // Best effort: close even if unpair returns a non-zero OSStatus. The
      // main Pairing view's own Unpair flow surfaces keychain errors; we
      // don't need to double up here.
      isPresented = false
    }
  }
}

// MARK: - Enter Code Sheet

private struct EnterCodeSheet: View {
  @Binding var isPresented: Bool
  @ObservedObject private var pairing = PairingStore.shared
  @State private var input: String = ""
  @State private var errorMessage: String?
  @State private var isPairing = false

  var body: some View {
    VStack(spacing: 20) {
      Text("Enter Pairing Code")
        .font(.headline)
      TextField("XXXX-XXXX-XXXX", text: $input)
        .textFieldStyle(RoundedBorderTextFieldStyle())
        .font(.system(.title2, design: .monospaced))
        .disabled(isPairing)
        .onChange(of: input) { newValue in
          let normalized = PairingStore.normalize(newValue)
          let limited = String(normalized.prefix(PairingStore.codeLength))
          let formatted = PairingStore.formatCode(limited)
          if formatted != newValue {
            input = formatted
          }
        }
      if let error = errorMessage {
        Text(error)
          .foregroundColor(.red)
          .font(.caption)
      }
      HStack {
        if isPairing {
          ProgressView()
            .controlSize(.small)
        }
        Spacer()
        Button("Cancel") {
          isPresented = false
        }
        .disabled(isPairing)
        .help("Close without pairing.")
        Button("Pair") {
          startPair()
        }
        .keyboardShortcut(.defaultAction)
        .disabled(isPairing)
        .help("Save the entered code as the pairing key on this Mac.")
      }
    }
    .padding(24)
    .frame(width: 420)
  }

  private func startPair() {
    let normalized = PairingStore.normalize(input)
    guard PairingStore.isValid(normalized) else {
      errorMessage = "Code must be 12 characters from the pairing alphabet."
      return
    }
    isPairing = true
    errorMessage = nil
    pairing.pair(withCode: normalized) { result in
      isPairing = false
      switch result {
      case .success:
        isPresented = false
      case .failure(let err):
        switch err {
        case .invalidCode:
          errorMessage = "Invalid code."
        case .derivationFailed:
          errorMessage = "Couldn't derive a key from that code."
        case .keychainFailed(let status):
          errorMessage = "Couldn't save the key to the keychain (error \(status))."
        }
      }
    }
  }
}

// MARK: - Preview

#Preview {
  PairingSettingsView()
}
